name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history for all branches and tags
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Build
        env:
          GOOS: windows
          GOARCH: amd64
        run: |
          go env          
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          ls
          mkdir out
          go build -o out/main.exe main.go
          ls
          ls out
          tar -cvzf lifecycle-v1+windows.x86-64.tgz out
          echo '123' > version.txt
      - uses: actions/upload-artifact@v2
        with:
          name: lifecycle-windows-x86-64
          path: lifecycle-v1+windows.x86-64.tgz
      - uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt
  sbom-windows:
    needs: build-and-publish
    runs-on: windows-2019
    steps:
      - name: Set git to use LF and symlinks
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global core.symlinks true
      - uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: actions/download-artifact@v2
        with:
          name: lifecycle-windows-x86-64
          path: sbom
      - uses: actions/download-artifact@v2
        with:
          name: version
          path: version.txt
      - name: Run
        shell: powershell
        env:
          GOOS: windows
          GOARCH: amd64
        run: |          
          cat version.txt >> $env:LIFECYCLE_VERSION
          cd sbom
          ls
          tar -xvzf *.tgz
          cd ..
          go env
          go run main.go -path .\sbom\out\main.exe
          cd sbom/out
          ls
          tar -zcvf sboms.tar.gz *.json
          echo ${{ env.LIFECYCLE_VERSION }}
      - uses: actions/upload-artifact@v2
        with:
          name: sbom-windows-x86-64
          path: sbom/out/sboms.tar.gz